### ISSUE TITLE
Error on launching exe

### ISSUE THREAD

**Issue by metacortexplus** [Guevara-chan/Midday-Commander#3]
![midday](https://user-images.githubusercontent.com/21023720/77824142-0faf1c00-7109-11ea-8b64-29849ed9f162.JPG)

Win 7

**Comment by Guevara-chan** [comment]
Hm... Looks like it crashes on raylib invocation. (line _180_ is `BeginDrawing()`).
But why ? Are `libraylib.dll` (just to be sure) in same dir as .exe ?

**Comment by Guevara-chan** [comment]
Could be related: https://github.com/raysan5/raylib/issues/1050

**Comment by metacortexplus** [comment]
> But why ? Are `libraylib.dll` (just to be sure) in same dir as .exe ?

Yes, it is in the same dir.
My Win 7 is x64 if it is matter.

**Comment by Guevara-chan** [comment]
OK, I see. Please, try new release I uploaded today: https://github.com/Guevara-chan/Midday-Commander/releases/tag/0.05
Hopefully, update to latest `raylib` (3.0) should fix this issue.

**Comment by metacortexplus** [comment]
Still get errors.
![error](https://user-images.githubusercontent.com/21023720/78032755-2b672c00-736e-11ea-9ffa-fe6239d963e4.JPG)

**Comment by Guevara-chan** [comment]
Well, I have exactly 1 additional idea. Try replacing `libraylib.dll` with this version:
[libraylib.zip](https://github.com/Guevara-chan/Midday-Commander/files/4409992/libraylib.zip)

**Comment by metacortexplus** [comment]
> 
> 
> Try replacing `libraylib.dll` with this version: [libraylib.zip](https://github.com/Guevara-chan/Midday-Commander/files/4409992/libraylib.zip)

Didn't help :)

**Comment by Guevara-chan** [comment]
Wait a moment. What's your videocard ? Are all drivers up to date ?

**Comment by metacortexplus** [comment]
It is integrated. It is laptop from 2010. Drivers should be up to date.
`Intel Mobile Intel 4 Series Express Chipset Family
	Manufacturer	Intel
	Model	Mobile Intel 4 Series Express Chipset Family
	Device ID	8086-2A42
	Revision	8
	Subvendor	HP (103C)
	Current Performance Level	Level 0
	Driver version	8.15.10.2057`
